# Generated by Django 2.2.7 on 2019-11-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=3)),
                ('location_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_code', models.CharField(max_length=10)),
                ('organization_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_location', to='user.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_code', models.CharField(max_length=20)),
                ('position_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Positon_on_Organization', to='user.Organization')),
            ],
        ),
    ]
